services:
  postgres:
    image: postgres:latest
    container_name: simulation_pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: